spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/ess_team11
    username: root
    password: mysql

  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 协议 默认就是smtp
    protocol: smtps
    # 发送者邮箱
    username: 1403724251@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: ttwxzrrvzzufbaae
    # 端口号465或587
    port: 465
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
URL: http://www.baidu.com/
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl